version: '3'
networks:
  net1:
    driver: bridge

services:
  db:
    image: 'mysql:5.7'
    restart: always
    container_name: db
    volumes:
      - './mysql/data:/var/lib/mysql'
      #- './config/mysql.conf.d:/etc/mysql/mysql.conf.d'
      - '/etc/localtime:/etc/localtime:ro'
    networks:
      - net1
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  apache:
    build: ./config/apache
    #image: 1and1internet/ubuntu-16-apache-php-7.2
    restart: always
    container_name: apache
    networks:
      - net1
    volumes:
      - '/etc/passwd:/etc/passwd'
      - '/etc/group:/etc/group'
      - '/etc/localtime:/etc/localtime:ro'
      - './config/hosts:/etc/hosts'

      - './config/apache2.conf:/etc/apache2/apache2.conf'
      - './config/default-ssl.conf:/etc/apache2/sites-available/default-ssl.conf'
      - './config/default-ssl.conf:/etc/apache2/sites-enabled/default-ssl.conf'

      - './config/ports.conf:/etc/apache2/ports.conf'
      - './config/php.ini:/etc/php/7.2/apache2/php.ini'
      - './config/ldap.conf:/etc/ldap/ldap.conf'
      - './certs:/etc/ssl'

      - '/site:/var/www/html'

      - './logs/apache/:/var/log/apache2'

    ports:
      - '80:80'
      - '443:443'
  #elk:
  #  image: willdurand/elk
  #  ports:
  #      - 81:80
  #  volumes:
  #      - ./elk/logstash:/etc/logstash
  #      - ./elk/logstash/patterns:/opt/logstash/patterns
    #volumes_from:
    #    - apache
